version: 2
jobs:
  GitLeaks:
    docker:
        - image: ruby:2.4.0
          environment:
            - LANG: C.UTF-8
    steps:
      - checkout
      - name: "Checking for credentials or tokens in code"
      - run: bash <(curl -s https://raw.githubusercontent.com/Zaulao/gitleaks-ci/master/gitleaks.sh)
